Part 3完成 柯振原
GenKoKo/ET-phase2-taipei-day-trip-website pull request #4
Opened 2021-05-22 04:16 UTC by GenKoKo

老師好，Part3完成了，還請檢查。

http://54.168.152.131:3000/
http://54.168.152.131:3000/attraction/1

但是part2搜尋部份，
還沒加上偵測enter的keydown事件處理，目前只有遊標點擊的搜尋事件。
我再快快加上enter的偵測。

2021-05-22 15:23 UTC, cwpeng requested changes
大部份都沒問題，但 RWD 的版面有嚴重的狀況，請優先處理我才能接受這個 PART 2 和 3 的成果哦。以下截圖是我在 1440px 寬度螢幕看到的結果，顯然是不行的。

我們設計圖稿出兩個有代表性的尺寸，一個是 1920px，前端工程師要補足 1200px 以上到 1920px 之間的所有桌機螢幕尺寸，概念就是內容要固定 1200px 置中。另一個是 360px，你要考慮的是所有手機尺寸，大約是 360px ~ 500px 之間。

關於這些想法請參考我們第一階段的第一個作業設計，每一個設計都是考慮過所有螢幕尺寸的狀況的。

2021-05-23 14:49 UTC, GenKoKo commented
感謝老師的提醒，
雖然我之前有試著去了解問題所在，
但覺得很怪奇的事，在css的設定上我都沒有設定width:1920px，只有設定width:100% / 100vw。
可能要再去看一下tutorial了解問題的所在。

2021-05-23 16:50 UTC, GenKoKo commented
老師好， 我已經將RWD的問題處理好，
原來是因為footer有copy到padding width的設定，所以導致版面錯亂。
還請老師再檢查一次了，感謝老師。

http://54.168.152.131:3000/
http://54.168.152.131:3000/attraction/1

2021-05-23 18:43 UTC, cwpeng commented
好哦，有改善很多，這樣就可以了，但請發一個 Review Request 給我，我才能幫你 approve，你也才能 merge ~

2021-05-23 22:29 UTC, GenKoKo commented
好的，我剛設定有re-request review了，不知是否正確呢？

2021-05-23 22:44 UTC, cwpeng approved these changes
OK 哦，記得 Merge Pull Request ~

2021-05-29 03:28 UTC, merged